"""
Crew orchestration module.
Sreves as an entry point for the agentic workflow
"""

from crewai import Crew, Process
from src.agent.agent import create_agent
from src.agent.tasks import create_tasks


def run_financial_crew(ticker : str) -> str:
    """
    Initializes and executes the financial analysis crew for a specific stock
    Args : stock ticker
    returns : final markdown report generated by the strategist agent

    """

    quant_agent, strategist_agent = create_agent()

    # assign the work
    task = create_tasks(
        quant_agent= quant_agent,
        strategist_agent= strategist_agent,
        ticker= ticker
    )

    # assemble the crew
    financial_crew = Crew(
        agents = [quant_agent, strategist_agent],
        tasks = task,
        process =  Process.sequential,
        verbose = True
              )
    
    # start the crew
    print(f"\n Kicking off financial analysis for {ticker}....")
    result =  financial_crew.kickoff()
    return result
